# Generated by Django 5.2.8 on 2025-11-17 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'analytics_archive',
                'ordering': ['-timestamp'],
            },
        ),
    ]
